/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Wii4Java_WiiListener */

#ifndef _Included_Wii4Java_WiiListener
#define _Included_Wii4Java_WiiListener
#ifdef __cplusplus
extern "C" {
#endif
#undef Wii4Java_WiiListener_CONNECTED
#define Wii4Java_WiiListener_CONNECTED 0L
#undef Wii4Java_WiiListener_ABORTED
#define Wii4Java_WiiListener_ABORTED 1L
#undef Wii4Java_WiiListener_ENDED
#define Wii4Java_WiiListener_ENDED 2L
#ifdef __cplusplus
}
#endif
#endif
