/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Wii4Java_Manager */

#ifndef _Included_Wii4Java_Manager
#define _Included_Wii4Java_Manager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Wii4Java_Manager
 * Method:    nConnect
 * Signature: (LWii4Java/WiiListener;)V
 */
JNIEXPORT void JNICALL Java_Wii4Java_Manager_nConnect
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Wii4Java_Manager
 * Method:    nDisconnect
 * Signature: (LWii4Java/WiiListener;)V
 */
JNIEXPORT void JNICALL Java_Wii4Java_Manager_nDisconnect
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
